format = """
$jobs\
$directory\
$git_branch\
$character\
"""

add_newline=false

[jobs]
format = '[\[$number\]](bold white) '
symbol_threshold = 1
number_threshold = 1

[directory]
truncation_length = 2
truncation_symbol = '.../'
format = '[$path](bold white)'

[git_branch]
format = ' on branch:[$branch(:$remote_branch)](bold white)'

[character]
success_symbol = '[>](bold white)'
error_symbol = '[>](bold white)'

